WITH l AS(
	SELECT *
	FROM AIRBNB.DBT_MYDEV.dim_listings_cleansed
),
h AS (
	SELECT *
	FROM AIRBNB.DBT_MYDEV.dim_hosts_cleansed_v2
)
SELECT
	l.LISTING_ID,
	l.LISTING_NAME,
	l.ROOM_TYPE,
	l.MINIMUM_NIGHTS,
	l.PRICE,
	l.HOST_ID,
	h.HOST_NAME,
	h.IS_SUPERHOST as HOST_IS_SUPERHOST,
	l.CREATED_AT,
	GREATEST(l.UPDATED_AT, h.UPDATED_AT) AS UPDATED_AT
FROM l
LEFT JOIN h ON (h.HOST_ID = l.HOST_ID)